# SPDX-FileCopyrightText: Tim Sutton
# SPDX-License-Identifier: MIT
name: 🐍 Python Checks
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v22
      - run: nix develop --command black --check --diff .
  ensure-utf8-encoding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v22
      - run: nix develop --command bash scripts/encoding_check.sh
  ensure-google-docstrings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v22
      - run: nix develop --command bash scripts/docstrings_check.sh
  test-count-feedback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v22
      - run: nix develop --command python scripts/commit_test_stats.py
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v22
      - run: nix develop --command isort --check --diff .
