# SPDX-FileCopyrightText: Tim Sutton
# SPDX-License-Identifier: MIT
name: ⚒️ QA Checks
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  code-size-feedback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v22
      - run: nix develop .#minimal --command bash scripts/codebase_size_check.sh
