# SPDX-FileCopyrightText: Tim Sutton
# SPDX-License-Identifier: MIT
name: 👨🏽 SQL Checks
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  sqlfluff-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v22
      - run: nix develop .#minimal --command sqlfluff lint sql/
  sqlfluff-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v22
      - run: nix develop .#minimal --command sqlfluff fix --check sql/
